#spring:
#  datasource:
#  url: jdbc:h2:tcp://localhost/~/reserve
#  username: sa
#  password:
#  driver-class-name: org.h2.Driver
#jpa:
#  hibernate:
#    ddl-auto: create
#  properties:
#    hibernate:
#      show_sql: true
#      format_sql: true
#    logging.level:
#      org.hibernate.type: trace #스프링 부트 2.x, hibernate5
#      org.hibernate.SQL: debug
#      org.hibernate.orm.jdbc.bind: trace #스프링 부트 3.x, hibernate6
# org.hibernate.orm.jdbc.bind: trace #스프링 부트 3.x, hibernate6
server:
  address: localhost
  port: 8080
  servlet:
    session:
      tracking-modes: cookie
spring:
  jackson:
    time-zone: Asia/Seoul
  datasource:
    url: jdbc:mysql://localhost:3306/reserveDB?serverTimezone=Asia/Seoul&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: sejongreservation1234@gmail.com
    password: aiuisqmggpmkbrsf
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
#    hikari:
#      poolName: MyHikariPool
#      maximumPoolSize: 10
#      minimumIdle: 2
#      idleTimeout: 30000
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true
      logging.level:
        org.hibernate.type: trace #스프링 부트 2.x, hibernate5

